In [1]:
from google.colab import files
uploaded = files.upload()

Saving Text data for sentiment analysis.csv to Text data for sentiment analysis.csv

In [2]:
import pandas as pd
df = pd.read_csv("Text data for sentiment analysis.csv")
df.head()

   id                                            comment sentiment
0   1                     আজকের দিনটি সাধারণভাবে কেটেছে।   neutral
1   2  আমি আজ বাজার থেকে যে পণ্যটি কিনেছি তা প্রত্যাশ...  negative
2   3                         ক্লাসটি আজ অনলাইনে হয়েছে।   neutral
3   4  আমি এই প্রকল্পের ফলাফল দেখে অভিভূত, সবার কঠোর ...  positive
4   5                         খাবারটি একদমই ভালো ছিল না।  negative

In [3]:
print(df.shape)
print(df.columns)
df['sentiment'].value_counts()

(2000, 3)
Index(['id', 'comment', 'sentiment'], dtype='object')

sentiment
neutral     685
positive    658
negative    657
Name: count, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['sentiment'] = le.fit_transform(df['sentiment'])

In [7]:
from sklearn.model_selection import train_test_split
x = df['comment']
y = df['sentiment']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print("Train:", len(x_train))
print("Test:", len(x_test))

Train: 1600
Test: 400

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x_train_cv = cv.fit_transform(x_train)
x_test_cv = cv.transform(x_test)

In [9]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [10]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(x_test_cv)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.915

In [13]:
sample = ["খাবারটি একদমই ভালো ছিল না।"]
sample_vec = cv.transform(sample)
prediction = model.predict(sample_vec)
print("Prediction:", prediction)

Prediction: [0]